/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopsb;

//import proyectopsb.VentanaAgregar;
//import proyectopsb.VentanaEditar;
import proyectopsb.VentanaLogin;
//import proyectopsb.VentanaMostrar;

/**
 *
 * @author FABRIZZIO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VolverAlLogin = new javax.swing.JLabel();
        btnAgregarPunto = new javax.swing.JLabel();
        btnMostrarPuntos = new javax.swing.JLabel();
        btnEditarPunto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        VolverAlLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverAlLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverAlLoginMouseClicked(evt);
            }
        });
        jPanel1.add(VolverAlLogin);
        VolverAlLogin.setBounds(20, 30, 90, 30);

        btnAgregarPunto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPuntoMouseClicked(evt);
            }
        });
        jPanel1.add(btnAgregarPunto);
        btnAgregarPunto.setBounds(60, 410, 320, 40);

        btnMostrarPuntos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarPuntos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarPuntosMouseClicked(evt);
            }
        });
        jPanel1.add(btnMostrarPuntos);
        btnMostrarPuntos.setBounds(60, 470, 320, 40);

        btnEditarPunto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPuntoMouseClicked(evt);
            }
        });
        jPanel1.add(btnEditarPunto);
        btnEditarPunto.setBounds(60, 530, 320, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 6, 410, 890);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverAlLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverAlLoginMouseClicked

        VentanaLogin ventana = new VentanaLogin();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_VolverAlLoginMouseClicked

    private void btnAgregarPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPuntoMouseClicked

        //VentanaAgregar ventana = new VentanaAgregar();
        //ventana.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnAgregarPuntoMouseClicked

    private void btnMostrarPuntosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarPuntosMouseClicked

        //VentanaMostrar ventanaM = new VentanaMostrar();
        //ventanaM.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMostrarPuntosMouseClicked

    private void btnEditarPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPuntoMouseClicked

        //VentanaEditar ventanaED = new VentanaEditar();
       // ventanaED.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnEditarPuntoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VolverAlLogin;
    private javax.swing.JLabel btnAgregarPunto;
    private javax.swing.JLabel btnEditarPunto;
    private javax.swing.JLabel btnMostrarPuntos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
