/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopsb;

import Clases.DatosCompartidos;
import Clases.PuntoCritico;
import Clases.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author JUAN
 */
public class VentanaEditar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEditar
     */
    Usuario usuarioActual;
    public VentanaEditar(Usuario usuarioActual) {
        initComponents();
        this.setLocationRelativeTo(null);
        for (PuntoCritico puntc : DatosCompartidos.puntosCriticos) {
        if (!contieneDistrito(cbDistritoBuscar, puntc.getDistrito())) {
            cbDistritoBuscar.addItem(puntc.getDistrito());
         }
       }
        this.usuarioActual = usuarioActual;
        lblUsuarioActual.setText("Usuario: "+usuarioActual.getNombre()+" || Correco: "+usuarioActual.getCorreo());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbDistritoBuscar = new javax.swing.JComboBox<>();
        cbDireccionBuscar = new javax.swing.JComboBox<>();
        cbNuevaPrioridad = new javax.swing.JComboBox<>();
        txtNuevaDireccion = new javax.swing.JTextField();
        txtNuevoDistrito = new javax.swing.JTextField();
        btnGuardarCambios = new javax.swing.JLabel();
        VolverAVentanaPrincipal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObservacion = new javax.swing.JTextArea();
        cbEstado = new javax.swing.JComboBox<>();
        lblUsuarioActual = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        cbDistritoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDistritoBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(cbDistritoBuscar);
        cbDistritoBuscar.setBounds(200, 90, 210, 30);

        cbDireccionBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDireccionBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(cbDireccionBuscar);
        cbDireccionBuscar.setBounds(200, 140, 210, 30);

        cbNuevaPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Alta", "Media", "Baja" }));
        cbNuevaPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNuevaPrioridadActionPerformed(evt);
            }
        });
        jPanel1.add(cbNuevaPrioridad);
        cbNuevaPrioridad.setBounds(180, 280, 140, 30);

        txtNuevaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtNuevaDireccion);
        txtNuevaDireccion.setBounds(170, 190, 230, 30);

        txtNuevoDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoDistritoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNuevoDistrito);
        txtNuevoDistrito.setBounds(170, 240, 230, 30);

        btnGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCambiosMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardarCambios);
        btnGuardarCambios.setBounds(50, 600, 150, 40);

        VolverAVentanaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverAVentanaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverAVentanaPrincipalMouseClicked(evt);
            }
        });
        jPanel1.add(VolverAVentanaPrincipal);
        VolverAVentanaPrincipal.setBounds(230, 600, 150, 40);

        txtAreaObservacion.setColumns(20);
        txtAreaObservacion.setRows(5);
        jScrollPane1.setViewportView(txtAreaObservacion);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 420, 360, 86);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Solucionado", "Solo Editar" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(cbEstado);
        cbEstado.setBounds(190, 330, 170, 30);
        jPanel1.add(lblUsuarioActual);
        lblUsuarioActual.setBounds(10, 10, 310, 20);

        btnAyuda.setText("Ayuda?");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAyuda);
        btnAyuda.setBounds(335, 13, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Editar nuevo 2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 881);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCambiosMouseClicked

    String distritoSeleccionado = (String) cbDistritoBuscar.getSelectedItem();
    String direccionSeleccionada = (String) cbDireccionBuscar.getSelectedItem();

    String nuevaDireccion = txtNuevaDireccion.getText().trim();
    String nuevoDistrito = txtNuevoDistrito.getText().trim();
    String nuevaPrioridad = (String) cbNuevaPrioridad.getSelectedItem();
    String nuevaObservacion = txtAreaObservacion.getText().trim();
    String estadoSeleccionado = (String) cbEstado.getSelectedItem();

    if (nuevaObservacion.length() > 200) {
    JOptionPane.showMessageDialog(this, "La observación no puede tener más de 200 caracteres.");
    return;
    }
    if (nuevaDireccion.isEmpty() || nuevoDistrito.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos");
        return;
    }
    
    if(estadoSeleccionado.equals("Solucionado")){
        nuevoDistrito += " (Solucionado)";
    }else{
        nuevoDistrito += " *";
    }

    for (PuntoCritico pb : DatosCompartidos.puntosCriticos) {
        if (pb.getDistrito().equals(distritoSeleccionado) && pb.getDireccion().equals(direccionSeleccionada)) {
            int respuesta = JOptionPane.showConfirmDialog(this, "Esta seguro de guardar los cambios?","confirma", JOptionPane.YES_NO_OPTION);
            if(respuesta != JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(this,"Cambios Caneclados");
                return;
            }
            
            pb.setDireccion(nuevaDireccion);
            pb.setDistrito(nuevoDistrito);
            pb.setPrioridad(nuevaPrioridad);
            pb.setObservacion(nuevaObservacion);
            
            JOptionPane.showMessageDialog(this, "Punto actualizado correctamente!");
            
            txtNuevaDireccion.setText("");
            txtNuevoDistrito.setText("");
            txtAreaObservacion.setText("");
            cbNuevaPrioridad.setSelectedIndex(0);
            cbEstado.setSelectedIndex(0);
            return;
        }
    }

    JOptionPane.showMessageDialog(this, "No se encontro el punnto para actualizar");
        
    }//GEN-LAST:event_btnGuardarCambiosMouseClicked

    private void VolverAVentanaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverAVentanaPrincipalMouseClicked

        this.setVisible(false);
        new VentanaPrincipal(usuarioActual).setVisible(true);
        
    }//GEN-LAST:event_VolverAVentanaPrincipalMouseClicked

    private void cbDistritoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDistritoBuscarActionPerformed

    cbDireccionBuscar.removeAllItems();
    String distritoSeleccionado = (String) cbDistritoBuscar.getSelectedItem();

    for (PuntoCritico p : DatosCompartidos.puntosCriticos) {
        if (p.getDistrito().equals(distritoSeleccionado)) {
            cbDireccionBuscar.addItem(p.getDireccion());
        }
    }
        
    }//GEN-LAST:event_cbDistritoBuscarActionPerformed

    private void cbDireccionBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDireccionBuscarActionPerformed

    }//GEN-LAST:event_cbDireccionBuscarActionPerformed

    private void txtNuevaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaDireccionActionPerformed

    }//GEN-LAST:event_txtNuevaDireccionActionPerformed

    private void txtNuevoDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoDistritoActionPerformed

    }//GEN-LAST:event_txtNuevoDistritoActionPerformed

    private void cbNuevaPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNuevaPrioridadActionPerformed

    }//GEN-LAST:event_cbNuevaPrioridadActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
       
        JOptionPane.showMessageDialog(this, "Para editar un punto Critico:\n" +
        "1. Selecciona el distrito y la direccion\n" +
        "2. Modifica los campos de direccion, distrito o prioridad\n" +
        "3. Presiona 'Guardar cambios'\n" +
        "Si algun campo esta vacio se mostrara un mensaje de advertencia",
        "Ayuda para editar", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private boolean contieneDistrito(javax.swing.JComboBox<String> combo, String distrito) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        if (combo.getItemAt(i).equals(distrito)) {
            return true;
        }
    }
       return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VolverAVentanaPrincipal;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JLabel btnGuardarCambios;
    private javax.swing.JComboBox<String> cbDireccionBuscar;
    private javax.swing.JComboBox<String> cbDistritoBuscar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbNuevaPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JTextArea txtAreaObservacion;
    private javax.swing.JTextField txtNuevaDireccion;
    private javax.swing.JTextField txtNuevoDistrito;
    // End of variables declaration//GEN-END:variables
}
