/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopsb;

import Clases.DatosCompartidos;
import Clases.PuntoCritico;
import Clases.Usuario;

import javax.swing.JOptionPane;
import proyectopsb.VentanaPrincipal;

/**
 *
 * @author FABRIZZIO
 */
public class VentanaAgregar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregar
     */
    Usuario usuarioActual;
    public VentanaAgregar(Usuario usuarioActual) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarioActual = usuarioActual;
        lblUsuarioActual.setText("Usuario: "+usuarioActual.getNombre()+" || Correco: "+usuarioActual.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDireccion = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        cbPrioridad = new javax.swing.JComboBox<>();
        btnGuardarPunto = new javax.swing.JLabel();
        VolverVentanaPrincipal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        lblUsuarioActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(120, 140, 270, 40);

        txtDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistritoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDistrito);
        txtDistrito.setBounds(120, 190, 270, 40);

        cbPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Alta", "Media", "Baja" }));
        cbPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrioridadActionPerformed(evt);
            }
        });
        jPanel1.add(cbPrioridad);
        cbPrioridad.setBounds(120, 290, 150, 30);

        btnGuardarPunto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarPuntoMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardarPunto);
        btnGuardarPunto.setBounds(40, 620, 150, 40);

        VolverVentanaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverVentanaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverVentanaPrincipalMouseClicked(evt);
            }
        });
        jPanel1.add(VolverVentanaPrincipal);
        VolverVentanaPrincipal.setBounds(250, 620, 160, 40);

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 430, 360, 86);
        jPanel1.add(lblUsuarioActual);
        lblUsuarioActual.setBounds(20, 20, 390, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar-1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 6, 420, 881);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed

    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistritoActionPerformed

    }//GEN-LAST:event_txtDistritoActionPerformed

    private void cbPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrioridadActionPerformed

    }//GEN-LAST:event_cbPrioridadActionPerformed

    private void btnGuardarPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarPuntoMouseClicked

        String direccion = txtDireccion.getText().trim();
        String distrito = txtDistrito.getText().trim();
        String prioridad = (String) cbPrioridad.getSelectedItem(); //metodo pa agarrar el valor que escojamos en el CB
        String observacion = txtObservacion.getText().trim();
        
        if(observacion.length() > 200){
            JOptionPane.showMessageDialog(this, "Se excedio el numero de caracteres disponibles en la Observacion por favor coloque  menos de 200 caracteres!");
            return;
        }
        
            if (direccion.isEmpty() || distrito.isEmpty() || prioridad.isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete todos los campos que dejo vacio!");
            return;
        }
            
            PuntoCritico nuevo = new PuntoCritico(direccion, distrito, prioridad, observacion);
            DatosCompartidos.puntosCriticos.add(nuevo);
            
            JOptionPane.showMessageDialog(this, "Punto Critico Registrado Correctamente!");
            
            txtDireccion.setText("");
            txtDistrito.setText("");
            cbPrioridad.setSelectedIndex(0);
            txtObservacion.setText("");

    }//GEN-LAST:event_btnGuardarPuntoMouseClicked

    private void VolverVentanaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverVentanaPrincipalMouseClicked
        this.setVisible(false);
        new VentanaPrincipal(usuarioActual).setVisible(true);
    }//GEN-LAST:event_VolverVentanaPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VolverVentanaPrincipal;
    private javax.swing.JLabel btnGuardarPunto;
    private javax.swing.JComboBox<String> cbPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextArea txtObservacion;
    // End of variables declaration//GEN-END:variables
}
