/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopsb;

import Clases.DatosCompartidos;
import Clases.Usuario;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ANGHELLO
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    public VentanaAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarLista();
    }
    
    private void actualizarLista(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        for(Map.Entry<String, Usuario> usu : DatosCompartidos.usuarios.entrySet()){
            String correo = usu.getKey();
            Usuario usuario = usu.getValue();
            if(!correo.equalsIgnoreCase("admin@admin.com")){
                lista.addElement(usuario.getNombre()+" - "+correo);
            }
        }
        jlistUsuariosRegistrados.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverLogin = new javax.swing.JLabel();
        btnEliminarUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistUsuariosRegistrados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnVolverLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnVolverLogin);
        btnVolverLogin.setBounds(250, 710, 150, 40);

        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(btnEliminarUsuario);
        btnEliminarUsuario.setBounds(40, 710, 150, 40);

        jScrollPane1.setViewportView(jlistUsuariosRegistrados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 180, 350, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 881);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverLoginMouseClicked
        
        VentanaLogin ventanaL = new VentanaLogin();
        ventanaL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverLoginMouseClicked

    private void btnEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseClicked
        
        List<String> usuSelect = jlistUsuariosRegistrados.getSelectedValuesList();
        
        if(usuSelect == null){
            JOptionPane.showMessageDialog(this, "Seleccione un usuario para eliminarlo!!");
            return;
        }
        
       int confirm = JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar al usuario seleccionado?", "confirmar", JOptionPane.YES_NO_OPTION);
       if (confirm != JOptionPane.YES_OPTION) return;

       for (String a : usuSelect) {
           String correo = a.split(" - ")[1].trim();
           if (!correo.equals("admin@admin.com")) {
               DatosCompartidos.usuarios.remove(correo);
           }
       }
       actualizarLista();
       JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
    }//GEN-LAST:event_btnEliminarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEliminarUsuario;
    private javax.swing.JLabel btnVolverLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistUsuariosRegistrados;
    // End of variables declaration//GEN-END:variables
}
