/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopsb;

import Clases.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class VentanaPerfil extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPerfil
     */
    Usuario usuarioActual;
    public VentanaPerfil(Usuario usuarioActual) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtNombre.setEditable(false);
        txtCorreo.setEditable(false);
        this.usuarioActual = usuarioActual;
        txtNombre.setText(usuarioActual.getNombre());
        txtCorreo.setText(usuarioActual.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContraseñaNueva = new javax.swing.JTextField();
        JpswordContraseñaAnterior = new javax.swing.JPasswordField();
        btnVolverVentanaPrincipal = new javax.swing.JLabel();
        btnCambiarContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(90, 290, 280, 40);

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(90, 360, 280, 40);

        txtContraseñaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraseñaNueva);
        txtContraseñaNueva.setBounds(30, 630, 340, 40);

        JpswordContraseñaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpswordContraseñaAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(JpswordContraseñaAnterior);
        JpswordContraseñaAnterior.setBounds(30, 530, 340, 40);

        btnVolverVentanaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverVentanaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverVentanaPrincipalMouseClicked(evt);
            }
        });
        jPanel1.add(btnVolverVentanaPrincipal);
        btnVolverVentanaPrincipal.setBounds(240, 730, 160, 40);

        btnCambiarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(btnCambiarContraseña);
        btnCambiarContraseña.setBounds(30, 730, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Perfil.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 881);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void JpswordContraseñaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpswordContraseñaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpswordContraseñaAnteriorActionPerformed

    private void txtContraseñaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaNuevaActionPerformed

    private void btnVolverVentanaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverVentanaPrincipalMouseClicked
       
        this.setVisible(false);
        new VentanaPrincipal(usuarioActual).setVisible(true);
    }//GEN-LAST:event_btnVolverVentanaPrincipalMouseClicked

    private void btnCambiarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarContraseñaMouseClicked
        String contraAnterior = new String(JpswordContraseñaAnterior.getPassword());
        String contraNueva = txtContraseñaNueva.getText().trim();
        
        if(!contraAnterior.equals(usuarioActual.getClave())){
            JOptionPane.showMessageDialog(this, "La contraseña actual no es la correcta!!");
            return;
        }
        
        if(contraNueva.length() < 8){
            JOptionPane.showMessageDialog(this, "La nueva Contraseña deve tener al menos 8 caracteres!!");
            return;
        }
        
        boolean veriSitieneMayusculas = false;
        for(char contra : contraNueva.toCharArray()){
            if(Character.isUpperCase(contra)){
                veriSitieneMayusculas = true;
                break;
            }
        }
        if(!veriSitieneMayusculas){
            JOptionPane.showMessageDialog(this, "La nueva Contraseña debe tener minimo 1 Letra Mayuscula!");
            return;
        }
        
        usuarioActual.setClave(contraNueva);
        JOptionPane.showMessageDialog(this, "Contraseña Actualizada Correctamente!!");
        JpswordContraseñaAnterior.setText("");
        txtContraseñaNueva.setText("");
    }//GEN-LAST:event_btnCambiarContraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JpswordContraseñaAnterior;
    private javax.swing.JLabel btnCambiarContraseña;
    private javax.swing.JLabel btnVolverVentanaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContraseñaNueva;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
