/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopsb;

import Clases.DatosCompartidos;
import Clases.PuntoCritico;
import Clases.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author JAFET
 */
public class VentanaBuscarDistrito extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscarDistrito
     */
    Usuario usuarioActual;
    public VentanaBuscarDistrito(Usuario usuarioActual) {
        initComponents();
        txtCantidadDistrito.setEditable(false);
        txtAreaResultados.setEditable(false);
        this.setLocationRelativeTo(null);
        for(PuntoCritico puntc : DatosCompartidos.puntosCriticos){
            if(!contieneDistrito(cbFiltroDistrito, puntc.getDistrito())){
                cbFiltroDistrito.addItem(puntc.getDistrito());
            }
        }
        this.usuarioActual = usuarioActual;
        lblUsuarioActual.setText("Usuario: "+usuarioActual.getNombre()+" || Correco: "+usuarioActual.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverVentanaPrincipal = new javax.swing.JLabel();
        btnMostrarPuntoElejido = new javax.swing.JLabel();
        cbFiltroDistrito = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultados = new javax.swing.JTextArea();
        txtCantidadDistrito = new javax.swing.JTextField();
        txtPalabraClave = new javax.swing.JTextField();
        btnBuscarporPalabra = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnVolverVentanaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverVentanaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverVentanaPrincipalMouseClicked(evt);
            }
        });
        jPanel1.add(btnVolverVentanaPrincipal);
        btnVolverVentanaPrincipal.setBounds(130, 740, 160, 50);

        btnMostrarPuntoElejido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarPuntoElejido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarPuntoElejidoMouseClicked(evt);
            }
        });
        jPanel1.add(btnMostrarPuntoElejido);
        btnMostrarPuntoElejido.setBounds(30, 670, 150, 40);

        jPanel1.add(cbFiltroDistrito);
        cbFiltroDistrito.setBounds(60, 160, 270, 40);

        txtAreaResultados.setColumns(20);
        txtAreaResultados.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 410, 340, 190);

        txtCantidadDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadDistritoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadDistrito);
        txtCantidadDistrito.setBounds(50, 210, 310, 30);
        jPanel1.add(txtPalabraClave);
        txtPalabraClave.setBounds(40, 330, 330, 40);

        btnBuscarporPalabra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarporPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarporPalabraMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarporPalabra);
        btnBuscarporPalabra.setBounds(240, 670, 160, 40);
        jPanel1.add(lblUsuarioActual);
        lblUsuarioActual.setBounds(10, 10, 390, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar nuevo 2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 880);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverVentanaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverVentanaPrincipalMouseClicked
        
        this.setVisible(false);
        new VentanaPrincipal(usuarioActual).setVisible(true);
    }//GEN-LAST:event_btnVolverVentanaPrincipalMouseClicked

    private void btnMostrarPuntoElejidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarPuntoElejidoMouseClicked
        String distritoSeleccionado = (String) cbFiltroDistrito.getSelectedItem();
        String resultado = "";
        int contador = 0;
        
        for(PuntoCritico punto : DatosCompartidos.puntosCriticos){
            if(punto.getDistrito().equalsIgnoreCase(distritoSeleccionado)){
                resultado += "Direccion: "+punto.getDireccion()+"\n";
                resultado += "Prioridad: "+punto.getPrioridad()+"\n";
                resultado += "Observacion: "+punto.getObservacion()+"\n";
                resultado += "====================================\n";
                contador++;
            }
        }
        if(resultado.isEmpty()){
            txtAreaResultados.setText("No se ecnotro el punto del Distrito seleccionado!");
            txtCantidadDistrito.setText("");
        }else{
            txtCantidadDistrito.setText("Cantidad de Puntos en este Distrito: "+ contador);
            txtAreaResultados.setText(resultado);
        }
    }//GEN-LAST:event_btnMostrarPuntoElejidoMouseClicked

    private void txtCantidadDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadDistritoActionPerformed

    private void btnBuscarporPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarporPalabraMouseClicked
        
        String palabraClave = txtPalabraClave.getText().trim().toLowerCase();
        String encontrado = "";
        
        if(palabraClave.isEmpty()){
            JOptionPane.showMessageDialog(this, "Escriba una palabra para Buscar!!!");
            return;
        }
        for(PuntoCritico punto : DatosCompartidos.puntosCriticos){
            if(punto.getObservacion().toLowerCase().contains(palabraClave)){
                encontrado += "Direccion: "+punto.getDireccion()+"\n";
                encontrado += "Distrito: "+punto.getDistrito()+"\n";
                encontrado += "Prioridad: "+punto.getPrioridad()+"\n";
                encontrado += "Observacion: "+punto.getObservacion()+"\n";
                encontrado += "==============================\n";
            }
        }
        if(encontrado.isEmpty()){
            txtAreaResultados.setText("No se ecnotro el punto del Distrito seleccionado!");
        }else{
            txtAreaResultados.setText(encontrado);
        }
    }//GEN-LAST:event_btnBuscarporPalabraMouseClicked

    private boolean contieneDistrito(javax.swing.JComboBox<String> combo, String distrito){
        for(int i = 0; i < combo.getItemCount(); i++){
            if(combo.getItemAt(i).equals(distrito)){
                return true;
            }
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaBuscarDistrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarporPalabra;
    private javax.swing.JLabel btnMostrarPuntoElejido;
    private javax.swing.JLabel btnVolverVentanaPrincipal;
    private javax.swing.JComboBox<String> cbFiltroDistrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JTextArea txtAreaResultados;
    private javax.swing.JTextField txtCantidadDistrito;
    private javax.swing.JTextField txtPalabraClave;
    // End of variables declaration//GEN-END:variables
}
